### ML Lab-08
# Ensemble Classification Methods
## Abdul Basit

### Tasks
##### Load iris dataset from scikit-learn.
Download the “Iris” dataset from scikit-learn dataset module and select only two features, “sepal length” and “petal width” and two classes, "setosa" and “versicolor”. Clean the data if required. Divide the data samples into train and test sets.
1. Train and test a decision tree classifier and report the achieved accuracies.
2. Repeat step 1 for bagging classifier using: model = BaggingClassifier(base_estimators = tree, n_estimators = 100, max_samples = 1.0, bootstrap = True, bootstrap_features = False, ran-dom_state = 1).
3. Apply boosting (using AdaBoost) on the same dataset using: model1 = AdaBoostClassi-fier(base_estimators = tree, n_estimators = 100, learning_rate = 0.1, random_state = 1).
4. Compare and comment the accuracies achieved in step 1 – 3.

In [2]:
#important Libraraies
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

In [3]:
iris = load_iris()

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [187]:
data = iris.data
col = iris.target

In [188]:
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [189]:
X= data[['sepal length (cm)','petal width (cm)']]
X.head()

sepal length (cm)  petal width (cm)
0                5.1               0.2
1                4.9               0.2
2                4.7               0.2
3                4.6               0.2
4                5.0               0.2

In [190]:
X['labels'] =  col
X

<ipython-input-190-750e9b2a4f03>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['labels'] =  col


sepal length (cm)  petal width (cm)  labels
0                  5.1               0.2       0
1                  4.9               0.2       0
2                  4.7               0.2       0
3                  4.6               0.2       0
4                  5.0               0.2       0
..                 ...               ...     ...
145                6.7               2.3       2
146                6.3               1.9       2
147                6.5               2.0       2
148                6.2               2.3       2
149                5.9               1.8       2

[150 rows x 3 columns]

In [191]:
X.shape

(150, 3)

In [195]:
new_data = X[X.labels != 2]
new_data.head()

sepal length (cm)  petal width (cm)  labels
0                5.1               0.2       0
1                4.9               0.2       0
2                4.7               0.2       0
3                4.6               0.2       0
4                5.0               0.2       0

In [196]:
new_data.shape

(100, 3)

In [197]:
X = new_data[['sepal length (cm)','petal width (cm)']]
X[:5]

sepal length (cm)  petal width (cm)
0                5.1               0.2
1                4.9               0.2
2                4.7               0.2
3                4.6               0.2
4                5.0               0.2

In [198]:
y = new_data[['labels']]
y.shape

(100, 1)

In [199]:
#Spliting data into train test set
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=24)

In [200]:
tree = DecisionTreeClassifier(criterion = 'entropy',random_state = 1, max_depth = None)
bag = BaggingClassifier(base_estimator = tree,
                      n_estimators = 10,
                       max_samples = 1.0,
                       max_features = 1.0,
                       bootstrap = True)


In [201]:
DTR = DecisionTreeRegressor(criterion='mse')
DTR.fit(x_train, y_train)

DecisionTreeRegressor()

In [202]:
y_predDTR = DTR.predict(x_test)
print('Accuracy of Decision Tree Regressor on test set: {:.2f}'.format(DTR.score(x_test, y_test)))

Accuracy of Decision Tree Regressor on test set: 1.00


In [203]:
DTC = DecisionTreeClassifier(criterion = 'entropy',random_state = 1, max_depth = None)
DTC.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=1)

In [204]:
y_predDTC = DTC.predict(x_test)
print(y_predDTC)

[0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1]


In [205]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(DTC.score(x_test, y_test)))

Accuracy of Decision Tree classifier on test set: 1.00


In [206]:
# Finding accuracy score
# accuracy_score(labels_test,pred)
DTC_acc_scr = accuracy_score(y_test,y_predDTC)
DTC_acc_scr

1.0

In [207]:
Bagging = BaggingClassifier(base_estimator=tree,n_estimators = 100, max_samples = 1.0, bootstrap = True, bootstrap_features = False, random_state = 1)
Bagging.fit(X, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                        random_state=1),
                  n_estimators=100, random_state=1)

In [208]:
Bagging_pred = Bagging.predict(x_test)
Bagging_pred 

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [209]:
Bagging_acc_scr = accuracy_score(y_test,Bagging_pred)
Bagging_acc_scr

1.0

In [210]:
ABC = AdaBoostClassifier(base_estimator=tree,n_estimators = 100, learning_rate = 0.1, random_state = 1)
ABC.fit(X, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                         random_state=1),
                   learning_rate=0.1, n_estimators=100, random_state=1)

In [211]:
ABC_pred = ABC.predict(x_test)
ABC_pred 

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1])

In [212]:
ABC_acc_scr = accuracy_score(y_test, ABC_pred)
ABC_acc_scr

1.0

In [213]:
tree = DecisionTreeClassifier(criterion = 'entropy',random_state = 1, max_depth = None)
bag = BaggingClassifier(base_estimator = tree,
                      n_estimators = 10,
                       max_samples = 1.0,
                       max_features = 1.0,
                       bootstrap = True)

In [214]:
cv = cross_val_score(tree,iris.data, iris.target, cv = 10)
print(cv)

[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 0.93333333 1.         1.        ]


In [215]:
tree_model = tree.fit(x_train,y_train)
Y_tree_pred = tree_model.predict(x_test)
print(Y_tree_pred)

[0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1]


In [216]:
tree_acc_scr = accuracy_score(Y_tree_pred,y_test)
print(tree_acc_scr)

1.0


In [217]:
bag_model = bag.fit(x_train,y_train)
Y_bag_pred = bag_model.predict(x_test)
print(Y_bag_pred)

[0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 1]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [218]:
bag_acc_scr = accuracy_score(y_test,Y_bag_pred)
print(bag_acc_scr)

1.0


In [219]:
fet = iris.data[:,[2,3]]
tar  = iris.target